2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_setup.py:_flush():69] setting env: {}
2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_init.py:_log_setup():336] Logging user logs to /home/jonas/Desktop/ATML/scratch/wandb/run-20210405_122959-1njeq4hx/logs/debug.log
2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_init.py:_log_setup():337] Logging internal logs to /home/jonas/Desktop/ATML/scratch/wandb/run-20210405_122959-1njeq4hx/logs/debug-internal.log
2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_init.py:init():369] calling init triggers
2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-04-05 12:29:59,528 INFO    MainThread:996989 [wandb_init.py:init():418] starting backend
2021-04-05 12:29:59,529 INFO    MainThread:996989 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-05 12:29:59,535 INFO    MainThread:996989 [backend.py:ensure_launched():123] starting backend process...
2021-04-05 12:29:59,538 INFO    MainThread:996989 [backend.py:ensure_launched():127] started backend process with pid: 997060
2021-04-05 12:29:59,539 INFO    MainThread:996989 [wandb_init.py:init():423] backend started and connected
2021-04-05 12:29:59,540 INFO    MainThread:996989 [wandb_init.py:init():463] updated telemetry
2021-04-05 12:29:59,540 INFO    MainThread:996989 [wandb_init.py:init():482] communicating current version
2021-04-05 12:29:59,915 INFO    MainThread:996989 [wandb_init.py:init():487] got version response 
2021-04-05 12:29:59,916 INFO    MainThread:996989 [wandb_init.py:init():495] communicating run to backend with 30 second timeout
2021-04-05 12:30:00,123 INFO    MainThread:996989 [wandb_init.py:init():520] starting run threads in backend
2021-04-05 12:30:00,149 INFO    MainThread:996989 [wandb_run.py:_console_start():1524] atexit reg
2021-04-05 12:30:00,149 INFO    MainThread:996989 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-05 12:30:00,150 INFO    MainThread:996989 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-05 12:30:00,150 INFO    MainThread:996989 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-05 12:30:00,151 INFO    MainThread:996989 [wandb_init.py:init():544] run started, returning control to user process
2021-04-05 12:30:00,152 INFO    MainThread:996989 [wandb_run.py:_config_callback():749] config_cb None None {'name': None, 'seed': None, 'epochs': 10, 'batch_size': 256, 'lr': 0.01, 'dry_run': False, 'wandb_log': True, 'wandb_key': None, 'sample_size': 64, 'dataset_size': 10000, 'all_latents': False, 'beta': 1}
2021-04-05 12:30:00,153 INFO    MainThread:996989 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-05 12:30:00,153 INFO    MainThread:996989 [wandb_run.py:_restore():1466] restore
2021-04-05 12:30:02,351 INFO    MainThread:996989 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 763
  total_bytes: 763
}

2021-04-05 12:30:04,354 INFO    MainThread:996989 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2609
  total_bytes: 2609
}

2021-04-05 12:30:05,402 INFO    MainThread:996989 [wandb_run.py:_show_files():1838] logging synced files
